project_name: bincapz

before:
  hooks:
    - go mod tidy

builds:
  # - id: bincapz
  #   binary: bincapz
  #   main: ./
  #   goos:
  #     - darwin
  #     # - linux
  #     # - windows
  #   goarch:
  #     # - amd64
  #     - arm64
  #     # - arm
  #   flags:
  #     - -trimpath
  #   mod_timestamp: '{{ .CommitTimestamp }}'
  #   ldflags:
  #     - -X main.BuildVersion={{.Version}}
  #   env:
  #     - CGO_ENABLED=1

  - id: darwin-amd64
    binary: bincapz-darwin-amd64
    no_unique_dist_dir: true
    env:
      - CC=o64-clang
      - CXX=o64-clang++
      - CGO_ENABLED=1
    main: ./
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - darwin
    goarch:
      - amd64

signs:
  - id: bincapz
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    cmd: cosign
    args: ["sign-blob", "--output-signature", "${artifact}.sig", "--output-certificate", "${artifact}.pem", "${artifact}"]
    artifacts: binary
  - id: checksum
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    cmd: cosign
    args: ["sign-blob", "--output-signature", "${artifact}.sig", "--output-certificate", "${artifact}.pem", "${artifact}"]
    artifacts: checksum

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc

snapshot:
  name_template: "{{ incpatch .Version }}-next"
