project_name: bincapz

before:
  hooks:
    - go mod tidy

builds:
  - id: bincapz-build
    binary: bincapz
    main: ./
    goos:
      - darwin
      - linux
      - windows
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -X main.BuildVersion={{.Version}}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc

snapshot:
  name_template: "{{ incpatch .Version }}-next"
