before:
  hooks:
    - go mod tidy

builds:
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -X main.BuildVersion={{.Version}}

    binary: bincapz

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc

signs:
  - artifacts: checksum
    cmd: gpg2
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

snapshot:
  name_template: "{{ incpatch .Version }}-next"
