issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/bincapz:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: chainguard-dev/bincapz/.github/workflows/(version|release).yaml@.*

permissions:
  contents: write
  pull-requests: write
