# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: check-goreleaser

on:
  pull_request:

permissions: {}

jobs:
  check-goreleaser:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/gythialy/golang-cross:v1.22.2-0@sha256:642fda874607057c34dfbb2d7fce93dfa37bdb9dbc0cc74835d9c3157a7a0e89

    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      # - name: install libyara-dev
      #   run: |
      #     sudo add-apt-repository -n -y "deb http://archive.ubuntu.com/ubuntu/ mantic main restricted universe multiverse"
      #     sudo add-apt-repository -n -y "deb http://archive.ubuntu.com/ubuntu/ mantic-updates main restricted universe multiverse"
      #     sudo add-apt-repository -n -y "deb http://archive.ubuntu.com/ubuntu/ mantic-backports main restricted universe multiverse"
      #     sudo add-apt-repository -n -y "deb http://security.ubuntu.com/ubuntu mantic-security main restricted universe multiverse"

          # sudo apt update && sudo apt install libyara-dev -y

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8 # v5.0.0
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --skip=sign --snapshot

      - name: check binaries
        run: |
          ./dist/bincapz_linux_amd64_v1/bincapz -h
